### ISSUE TITLE
OneWire is required to compile Telemetrix4Esp8266.ino

### ISSUE THREAD

**Issue by Anton-V-K** [MrYsLab/Telemetrix4Esp8266#3]
`Telemetrix4Esp8266` depends on `Ultrasonic` and `DHTStable`, which are installed by the library manager automagically.
However `Telemetrix4Esp8266.ino` also requires OneWire library, which may be missing on a particular PC:
```
Telemetrix4Esp8266:26:10: fatal error: OneWire.h: No such file or directory
   26 | #include <OneWire.h>
      |          ^~~~~~~~~~~
```
I think, the dependency on `OneWire` should be added to `library.properties`.

Workaround: install [OneWire](https://www.pjrc.com/teensy/td_libs_OneWire.html) manually (via Library Manager)

**Comment by MrYsLab** [comment]
I published release 3.0.1 to the Arduino library manager. It should be made available by Arduino in the next day or so.
